### ISSUE TITLE
Grafana: Add dashboard for components on boot servers

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#1011]
## What

We want to watch metrics of components on boot servers, such as CKE, etcd, and sabakan.
Add grafana dashboard for components on boot servers.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
We have dashboards for etcd on boot servers and sabakan already.
As to CKE, "explore" is enough to check the reboot queue length.
Closing.
