### ISSUE TITLE
neco-apps: Upgrade ArgoCD to V1.6.0 and enable support for aggregated ClusterRoles.

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1016]
## What

The rook manifests use Aggregated ClusterRoles and it causes  ArgoCD's misdetection of OutOfSync, if not set [complex ignoring rules](https://github.com/cybozu-go/neco-apps/blob/9153a7c1dd5fe8a3a8ca47b6cfe788534791537b/argocd-config/base/rook.yaml#L21-L66).

To simplify the rules, enable the `ignoreAggregratedRoles` feature which is supported by ArgoCD v1.6.0-rc1 or later.

ref: 

Aggregated ClusterRoles
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles

ignoreAggregatedRoles
https://github.com/argoproj/argo-cd/issues/2382
https://github.com/argoproj/argo-cd/pull/3076

## How

- Upgrade ArgoCD to V1.6.0
- Enable `ignoreAggregatedRoles` feature
- Delete [ignoring rules](https://github.com/cybozu-go/neco-apps/blob/9153a7c1dd5fe8a3a8ca47b6cfe788534791537b/argocd-config/base/rook.yaml#L21-L66) which just exist in the feature branch: rook-revenge.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by tapih** [comment]
v1.6.1 is released. https://github.com/argoproj/argo-cd/tree/v1.6.1
