### ISSUE TITLE
Rook: avoid dependency on udev persistent device names in handling OSDs

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#1030]
## What

In OSD on LV-backed PVC, Rook handles OSDs with udev persistent device names (in short,
udev names) like "/dev/<vgname>/<lvname>" even though the PVs are provisioned with using
the non-udev device names. However, sometimes, udev names aren't created by accident.
Then Ceph fails to launch the OSDs that don't have udev names.

Currently, we bypass this problem with running `udevadm trigger` periodically. However, we
don't want to use it permanently. It's better to use the non-udev device names that are used
in provisioning the corresponding PVs. 

## How

There are two ways.

a. Use raw mode OSD in OSD on LV-backed PVC. Then Rook uses the device names that are used
    in provisioning PVs.
b. Use the device names that are used to provision PVs, even if OSD on LV-backed PVC.

First, we should evaluate which way is better.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by llamerada-jp** [comment]
after apply osd raw mode patch, this issue is resolved.
ref. https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/neco/1088
