### ISSUE TITLE
CKE: unify OperatorsSuite and RobustnessSuite in mtest

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#1031]
## What

`OperatorSuite` and `RobustnessSuite` in `mtest/suites.go` call the same test function `TestOperators()` under slightly different conditions; `RobustnessSuite` stops a certain control plane before calling while `OperatorSuite` does not.
They should be unified.

## How

Unify to stop a control plane as `RobustnessSuite` does.

Some tests in `TestOperators()` are executed only when they are called from `OperatorSuite` because they expect stability and reproducibility for the states of control planes.
Improve such tests to run under the condition of degraded control planes.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
This is not worth doing.
