### ISSUE TITLE
rook: Disappear LV tags after node reboot

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1042]
## What

In rare cases, LV tags which are added by `ceph-volume prepare` are disappeared after node reboot.
It causes OSD Pods crash. Let's prevent it!

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Superseded by https://github.com/cybozu-go/neco-apps/pull/737
