### ISSUE TITLE
[CKE] Suppress insufficient cluster reconstruction when recovering from blackout

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/neco#1048]
## What

Suppress insufficient cluster reconstruction when recovering blackout.
see: [KPT Topic](https://bozuman.cybozu.com/k/33251/show#record=1220&l.view=5350792&l.q=f5700079%2520%253E%253D%2520FROM_TODAY%28-7%252C%2520DAYS%29%2520and%2520f5700079%2520%253C%2520TODAY%28%29%2520and%2520f5350785%2520in%2520%28%25225350783%2522%29&l.sort_0=f5350774&l.order_0=ASC&l.next=1222&l.prev=0)

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
The said problem was that CKE might change the cluster configuration too drastically
when recovering from a total data center blackout.

However, I don't think anything needs to be changed for the following reasons.

- CKE does not remove existing nodes unless they are retired.  It only adds extra nodes.
- CKE may replace at most one control-plane node with a worker node.

@kfyharukz
