### ISSUE TITLE
Auto recovery the number of OSDs when machines are retired

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1055]
## What

When the machine is retired, the OSDs running on it will not be able to run.
Let's improve the reconcile function of Rook, to detect and auto-recovery this situation.

## How

T.B.D.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#10
