### ISSUE TITLE
Remove unused PVCs which remain undeleted by regeneration of MON.

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1058]
## What

Remove unused PVCs which remain undeleted by regeneration of MON.
- [related operation](https://github.com/cybozu-private/neco-ops/issues/529)

## How

- Remove the PVCs by operations periodically.
- Create a template for the operation.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#40
