### ISSUE TITLE
Enable to access grafana dashboard for production from regular terminals

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#1064]
## What

Grafana dashboard for production does not contain sensitive information and is okay to permit accesses from regular terminals.
Therefore, enable to access Grafana dashboard for production from regular terminals.

- Note
  - As the logging information may contain sensitive information, Loki's dashboard should allow accesses only from operational terminals. See [this](https://bozuman.cybozu.com/k/33251/show#record=1241) for details. 

## How

**NEVER FORGET TO ASK IT DEPT. TO MAKE REQUESTS TO GRAFANA GO THROUGH PROXY AGAIN**
T.B.D

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zoetrope** [comment]
#dup
