### ISSUE TITLE
Consider how long GCP VM instances should be extended

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#1083]
## What

Currently, GCP instances are extended until 21:00 p.m. by slack extend notification.
Though, as it extends too long and is costly, consider better way to extend GCP instances.

## How

The detail is not fixed yet.
My thinking: https://bozuman.cybozu.com/k/#/space/3801/thread/25931/2510747/3732202

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
There's no problem with the current values.
