### ISSUE TITLE
Ubuntu 20.04 support of dctest

### ISSUE THREAD

**Issue by umezawatakeshi** [cybozu-go/neco#1087]
## What

make dctest be able to run on Ubuntu 20.04 machine.

note: this issue is different from #741

## How

- update neco, neco-apps, placemat, etc

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zoetrope** [comment]
rkt cannot work
