### ISSUE TITLE
[sabakan] improve sabactl machines get

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1089]
## What

Improve `abactl machines get` command's options.

## How

Improve the options for filtering nodes as follows.

- Use `,` to specify multiple conditions like `--rack 1,2`.
- Use `--without` as in `--without-ipv4` to specify a negative condition.
- When `--without-hoge` and `--hoge` are specified at the same time, rise the errors.

Improve output format like `kubectl -o wide`

- implement `-o simple` option
- The output columns are below. 
  - serial
  - rack
  - role
  - status
  - first item of ipv4
  - ipv4 in bmc
- https://golang.org/pkg/text/tabwriter/

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by kmdkuk** [comment]
Commands that use the same selector

- `neco reboot-worker`
- `neco isoreboot`
- `neco apply-firmware`

It probably uses the sabakan package, but I haven't been able to confirm that.
Also, there may be other commands that use the same selector.
