### ISSUE TITLE
Deploy pvc-autoresizer

### ISSUE THREAD

**Issue by yokaze** [cybozu-go/neco#1096]
## What

Deploy pvc-autoresizer.

## How

- Add manifest in neco-apps to deploy pvc-autoresizer.
- Configure storage class to enable pvc-autoresizer.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@yokaze 

> Discuss resizing strategy with Maneki team.

I don't think this is necessary at this stage.
We can leave the decision to Maneki.
