### ISSUE TITLE
neco-containers: upgrade misc container images for K8s 1.18

### ISSUE THREAD

**Issue by tapih** [cybozu-go/neco#1106]
## What

To Upgrade k8s to v1.18, prepare container images.

## How

- [x] cke-tools
- [x] pause
- [x] CoreDNS
- [x] Unbound
- [x] kube-state-metrics
- [x] metrics-server
- [x] kubectl in ArgoCD
- [x] etcd

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by tapih** [comment]
#### CNI Plugins

v0.8.6 -> v0.8.7 Nothing notable
https://github.com/containernetworking/plugins/releases

**Comment by tapih** [comment]
#### pause

Nothing to be done.

**Comment by yokaze** [comment]
#### CoreDNS
v1.6.7 -> v1.7.0 Some metrics names changed, but none of them are used.

**Comment by yokaze** [comment]
## Unbound
v1.10.1 -> v1.11.0 Nothing notable
https://github.com/NLnetLabs/unbound/releases/tag/release-1.11.0

**Comment by tapih** [comment]
#### kube-state-metrics
1.9.5 -> 1.9.7 Nothing notable
https://github.com/kubernetes/kube-state-metrics/releases
