### ISSUE TITLE
coil: Update for k8s 1.18

### ISSUE THREAD

**Issue by umezawatakeshi** [cybozu-go/neco#1109]
## What

Update coil for k8s 1.18

## How

* Update support versions
* Update outdated example

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by tapih** [comment]
Coil v1 is expected to run on k8s 1.18 without any modification and Coil v2 is being developed, so basically this does not need to be updated.
