### ISSUE TITLE
CKE and neco: release for k8s 1.18

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#1114]
## What

Release CKE for k8s 1.18, and include it to Neco.
Send the sonobuoy result of CKE 1.18.0 to the authorities.

## How

Release CKE:
Follow the steps in [RELEASE.md](https://github.com/cybozu-go/cke/blob/master/RELEASE.md).

Update Neco:
Follow the steps in [cicd.md](https://github.com/cybozu-go/neco/blob/master/docs/cicd.md).

Send sonobuoy result:
Create a PR in [cncf/k8s-conformance](https://github.com/cncf/k8s-conformance).
See [RELEASE.md](https://github.com/cybozu-go/cke/blob/master/RELEASE.md) for more detail.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by umezawatakeshi** [comment]
sent conformance results: https://github.com/cncf/k8s-conformance/pull/1153
