### ISSUE TITLE
Introduce Cilium for NetworkPolicy

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#1120]
## What

Introduce Cilium as a NetworkPolicy implementation instead of Calico.
Calico has performance and observability issues, because it uses iptables.

## How

* Create the container images for Cilium
* Add manifests to deploy Cilium
* Modify the cni configuration file to use cilium-cni plugin
  * https://docs.cilium.io/en/v1.8/gettingstarted/cni-chaining-generic-veth/
* Rewrite NetworkPolicy resources from Calico to Cilium
* Deploy Hubble and Hubble-UI
  * https://github.com/cilium/hubble
  * https://github.com/cilium/hubble-ui

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ysksuzuki** [comment]
We are going to work on #1776
