### ISSUE TITLE
Remove dashboard panels using missing metrics

### ISSUE THREAD

**Issue by yokaze** [cybozu-go/neco#1142]
## What

The following metrics are not correctly collected.
- `network_plugin_operations_latency_microseconds`

It should be removed from Grafana because it is not so important.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ysksuzuki** [comment]
Remove the panel using `network_plugin_operations_latency_microseconds` because containerd has no metrics related to `network_plugin_operations_latency_microseconds`
