### ISSUE TITLE
[neco] use scheduler profile on OSD pod

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1156]
## What

- Enable scheduler profile for OSD pod.

## How

- rook: Enable scheduler profile name.
  ref. https://github.com/rook/rook/pull/5630

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zoetrope** [comment]
ref #988
