### ISSUE TITLE
Rook/Ceph: Backup and restore of rook/ceph metadata

### ISSUE THREAD

**Issue by toshipp** [cybozu-go/neco#1161]
## What

- Servey how to backup and restore of rook/ceph metadata
- Consider a backup storategy
- Make a backup service for metadata
- Write a document for a restoration

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by llamerada-jp** [comment]
It was decided not to work on this task based on the following description.
- https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html/troubleshooting_guide/troubleshooting-ceph-monitors#recovering-the-ceph-monitor-store
- http://lists.ceph.com/pipermail/ceph-users-ceph.com/2018-November/031224.html
