### ISSUE TITLE
Ubuntu 20.04: GCP VM image

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#1166]
## What

Change GCP VM base image from Ubuntu 18.04 to 20.04.

## How

As we cannot depend on `rkt` now, we need to wait for the new placemat v2.
Also, re-enable [swtpm](https://github.com/stefanberger/swtpm) to test TPM-capability of `sabakan-cryptsetup`.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ysksuzuki** [comment]
TPM is already activated [here](https://github.com/cybozu-go/neco/pull/1458)
