### ISSUE TITLE
Move GCP instance settings from neco to neco-gcp

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/neco#1169]
## What

Some GCP instance settings are remaining in `cybozu-go/neco` repository.
It can make inconsistency, so we should move these settings to `cybozu-go/neco-gcp`.

## How

- Move GCP instance settings from `neco` to `neco-gcp`.
- Use `necogcp` command to create CI environment

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by tapih** [comment]
Closed because this issue is going to be unnecessary by https://github.com/cybozu-go/neco/issues/1209 .
