### ISSUE TITLE
Run nmap from outside the company

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1177]
## What

To improve security, regularly run nmap from outside the company.

## How

Run `nmap` periodically from within GitHub Actions and alert warning if unexpected ports are opened.
https://futurestud.io/tutorials/github-actions-trigger-builds-on-schedule-cron

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@masa213f Please move this to neco-ops.
