### ISSUE TITLE
Set failed OSDs to out automatically when a rack or node is down

### ISSUE THREAD

**Issue by toshipp** [cybozu-go/neco#1236]
## What

Currently, ceph monitor doesn't set OSDs to out when a rack is down or node is retired.

Possibly the configuration of `mon osd down out subtree limit` is related.
https://docs.ceph.com/en/latest/rados/configuration/mon-osd-interaction/

## How

Describe how to address the issue.

- Set ceph parameter to make the osd be out after timeout after node is down

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by llamerada-jp** [comment]
Please check this PR.
https://github.com/rook/rook/pull/6999

**Comment by toshipp** [comment]
move to cybozu/csa#19
