### ISSUE TITLE
Fix alert rule `CKESabakanIntegrationDoesNotPerformAnyOps`

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/neco#1244]
## What

The alert rule `CKESabakanIntegrationDoesNotPerformAnyOps` is triggered when a leader change occurs, even it is normal behavior.

## How

Fix the rule.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by morimoto-cybozu** [comment]
Already improved by https://github.com/cybozu-go/neco-apps/pull/900.
