### ISSUE TITLE
[Rook/Ceph] disable or ignore device_health_metrics pool

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1247]
## What

- Disable or ignore `device_health_metrics` pool to avoid  extra HEALTH_WARN.
- Disable devicehealth module without manual operation.
- [related posts](https://bozuman.cybozu.com/k/#/space/3801/thread/38010/2632127/4189327)

### Additional Information

"device_health_metrics" pool will be renamed to ".mgr" pool, which will be used by all mgr modules. So simply deleting this pool would be not suitable. Instead, probably, we should change its crush rule to the one for user data.

```
ceph osd pool set <pool-name> crush_rule <rule-name>
```

We may be able to automate this operation in Rook's layer. However, we should discuss the cost-effectiveness of this change since it would be only one operation for each cluster.

Reference:
https://docs.ceph.com/en/latest/mgr/administrator/#module-pool
```
The manager creates a pool for use by its module to store state. The name of this pool is .mgr (with the leading . indicating a reserved pool name).

Note

Prior to Quincy, the devicehealth module created a device_health_metrics pool to store device SMART statistics. With Quincy, this pool is automatically renamed to be the common manager module pool.
```

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#18
