### ISSUE TITLE
[Rook/Ceph] stop using rootFilesystem by mon

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1253]
## What

- Stop using rootFilesystem by mon to avoid rapid storage utilization that would cause eviction in the node.
- [related post](https://bozuman.cybozu.com/k/#/space/3801/thread/27736/2660213)

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#34
