### ISSUE TITLE
Cannot create Kibana under the pod security policy readOnlyRootFilesystem=true.

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1261]
## What

ECK v1.2 or greater, We cannot create Kibana under the pod security policy `readOnlyRootFilesystem=true`.

We reported this problem to the upstream repository. https://github.com/elastic/cloud-on-k8s/issues/4022
Tracking this issue and upgrade ECK if the new version is released.

## How

- Watch https://github.com/elastic/cloud-on-k8s/issues/4022
- Add a test for deploying Kibana to verifying the fix of the problem.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
PSP will be removed.
