### ISSUE TITLE
[Rook/Ceph] Purge osd when a node becomes unhealthy or retire

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1266]
## What

- Purge osd when a node becomes unhealthy or retired.
- If the osd pod is restarted while node unhelathy, it will fail to schedule the pod.

## How

Describe how to address the issue.

- Possibly some new controller should purge the osd if the event happens.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#35
