### ISSUE TITLE
[CKE] Add Validation for `KubeletConfiguration`

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#1298]
## What

The current CKE may implicitly ignore the user's `kubelet` setting.
To avoid this, please implement the validation for `kubelet`.

Related PR: https://github.com/cybozu-go/cke/pull/399

## How

T.B.D.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by morimoto-cybozu** [comment]
As of CKE 1.19, the old style configuration is no longer supported.
The new style configuration is automatically validated by typed unmarshal, so this task can be cancelled.
