### ISSUE TITLE
Enhance dashboard for TopoLVM

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1342]
## What

- Outputs a graph of the usage rate.
- After [this issue](https://github.com/topolvm/topolvm/issues/248).

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#33
