### ISSUE TITLE
[Rook/Ceph] Adjust the parameters to prevent OSD/MON from failover when rebooting the node.

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1343]
## What

Adjust the parameters to prevent OSD/MON from failover when rebooting the node.
With the current configuration, it starts failover in about 15 minutes. Since it may take up to 30 minutes to restart a node, adjust the threshold before failover starts.

## How

TBD

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#16
