### ISSUE TITLE
[setup-hw] Performance tuning for dell servers

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#1381]
## What

Currently, some parameters related to NUMA are disabled or set to a small number.
Update setup-hw to tune the parameters for better performance.

See more details [here](https://bozuman.cybozu.com/k/#/space/3801/thread/25931/2668265/4415227).

## How

* Upgrade OMSA

T.B.D.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zeroalphat** [comment]
fixed
https://github.com/cybozu-go/setup-hw/pull/73
