### ISSUE TITLE
sabakan: Remove UPDATING state

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1385]
## What

Sabakan's `UPDATING` state is not being used.
If the state is no longer needed, it is good to remove the state.

## How

- Check whether we can delete it.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
I merge this to #815
