### ISSUE TITLE
Rook/Ceph: apply priorityClass for CrashCollector

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1400]
## What

CrashCollector need higher priority to schedule in preference to other pods.

## How

need patch for Rook upstream to set priorityClass for CrashCollector pod.
- https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html#priority-class-names-configuration-settings
- https://bozuman.cybozu.com/k/#/space/3801/thread/27736/2744997/4472334

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#17
