### ISSUE TITLE
containerd does not fallback when the error code returned by Registry Mirror is other than 404

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#1409]
**Describe the bug**

containerd does not fallback when the error code returned by Registry Mirror is other than 404.
For example, if a ObjectBucket for Registry Mirror fails to be deployed.

ref: https://github.com/containerd/containerd/issues/4531

**Environments**
- Version:
- OS:

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by umezawatakeshi** [comment]
This feature is already implemented by upstream.
