### ISSUE TITLE
Collect session logs of the users who access via SSH.

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1411]
## What

Collect session logs of the users who access via SSH.

## How

- Insert a script to get the log when accessing SSH.
- Save the captured log to Loki via fluent-bit.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@toshipp @llamerada-jp @satoru-takeuchi 
Please consider using `ForceCommand` to force `script`.

```
    ForceCommand
             Forces the execution of the command specified by ForceCommand, ignoring any command supplied by the client and
             ~/.ssh/rc if present.  The command is invoked by using the user's login shell with the -c option.  This applies to
             shell, command, or subsystem execution.  It is most useful inside a Match block.  The command originally supplied by
             the client is available in the SSH_ORIGINAL_COMMAND environment variable.  Specifying a command of internal-sftp will
             force the use of an in-process SFTP server that requires no support files when used with ChrootDirectory.  The default
             is none.
```

**Comment by umezawatakeshi** [comment]
It is much better to use object bucket as the storage than to use loki because the session replay log generated by `script` is not a line-based timestamped text log.
