### ISSUE TITLE
Drop Prometheus resources

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#1414]
## What

As the final step of the transition from Prometheus to VictoriaMetrics,
Prometheus-related resources should be purged from neco-apps.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by umezawatakeshi** [comment]
duplicate #1360
