### ISSUE TITLE
Loki: replace client from Promtail to fluent-bit

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1469]
## What

Replace client from Promtail to fluent-bit.
Because Promtail may lose the log when it crashes.

## How

- add build scripts for `fluent/fluent-bit` in neco-containers.
  - maintain `maintenance.md`.
- edit neco-apps Makefile to replace Promtail with fluent-bit.
- migrate client's rule to collect the same logs.
  - maintain the rule to try to remove the label of filename without log missing.
  - maintain the rule to collect audit log.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
We observed that the current fluent-bit tends to be paused when it sends logs to loki.
It is related to log out-of-order constraint of loki. see https://github.com/fluent/fluent-bit/issues/3082.
Now close the issue due to lack of our resources.
