### ISSUE TITLE
[neco-wiki] Add GitHub Actions tutorial

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#1502]
## What

We are now switching to GitHub Actions. So, it is good to have a tutorial document in neco-wiki.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by yokaze** [comment]
We've been switched to use GitHub Actions already; no need to write an internal tutorial.
