### ISSUE TITLE
Prepare for the 2nd GameDay

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#1530]
## What

We need to address the simulated incident in the incoming 2nd GameDay.
Make it clear what to do for the expected incident.

## How

Investigate the contents of Neco wiki closely and make a concrete procedure for the expected incident.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by tapih** [comment]
Close this because this should be registered on neco-ops.
