### ISSUE TITLE
Confirm stabilty of RGW when rook operator is crash-looping

### ISSUE THREAD

**Issue by toshipp** [cybozu-go/neco#1534]
## What

We observed that RGW is unexpectedly crash-looping.
When the event happened, the first time, ceph health became warn, and then the rook operator is crashed due to segv.
The segv issue is already fixed in upstream https://github.com/rook/rook/pull/7280 and will be shipped as of 1.6.
We suspect that the rook operator crash causes RGW crash-looping.
Therefore we confirm RGW is stable when such an event.

## How

- crash rook operator many times manually, then confirm if RGW is stable.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by llamerada-jp** [comment]
When it reproduces, confirm again.
