### ISSUE TITLE
Experiment on Linux pstore with Flatcar Container Linux

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#1535]
## What

Experiment on Linux pstore with Flatcar Container Linux to clarify whether pstore is usable on Neco's worker nodes or not.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@morimoto-cybozu What will you do about this?  It's too ambiguous.

**Comment by morimoto-cybozu** [comment]
@ymmt2005 
The goal of this issue is to clarify whether pstore is usable on Neco's worker nodes, and I've updated the issue text.

We have performed the experiment in cybozu-private/neco-ops#977.
The subsequent tasks, cybozu-private/neco-wiki#468, cybozu-private/neco-wiki#470, and neco#1541, are done.
So this issue should be closed.

**Comment by ymmt2005** [comment]
Got it.
