### ISSUE TITLE
monitoring physical storage

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1539]
## What

Monitoring physical storage using SMART via node-exporter.

## How

- Export metrics of SMART using node-exporter.
- Collect metrics using VectoriaMetrics.
- Add or configure dashboard.
- Add some alerts for physical storage if needed.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#39
