### ISSUE TITLE
Quickly recover etcd

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#1552]
## What

When we shutdown a boot server, it takes 15 minutes for etcd to come back.
We want to shorten the recovery time.

## How

This problem may be solved in etcd 3.4. Let's give it a try.
ref. https://github.com/etcd-io/etcd/issues/7941

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by yokaze** [comment]
The problem still exists when we use etcd 3.4.
