### ISSUE TITLE
local-pv-provisioner:  add the way not to create PVs for specific devices

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#1571]
## What

We don't have a filter not to create PVs for specific devices. It cause a problem when retiring an device, which backs an OSD. In this case, we remove the corresponding PV from Ceph cluster. However, after that, the new PV will be created and this might be used  for OSD again.

## How

TBD

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#32
