### ISSUE TITLE
Debug and update VictoriaMetrics

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#1572]
## What

VictoriaMetrics 1.57 and later have some bug around scrape target recognition using K8s service discovery.
Investigate the bug and update VictoriaMetrics.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
resolved with VM 1.60
