### ISSUE TITLE
rook: ceph: fix liveness probe of RGW to be regarded as alive on resharding.

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#1575]
## What

If there are many objects (over 10 milions) in RGW, liveness probe fails during dynamic resharding.

See the following links.
https://bozuman.cybozu.com/k/#/space/3801/thread/38010/2873440
https://github.com/rook/rook/issues/6304

## How

TBD

It's unsure the root cause. If RGW service becomes unavailable during resharding, we should fix Ceph. Or if Rook's liveness probe method is wrong, we should fix it.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#14
