### ISSUE TITLE
Rook/Ceph: export metrics of object count in RGW

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1582]
## What

We can not get object count in RGW by metrics of Rook/Ceph. This metrics helps us to know usage situation.

## How

TBD

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#30
