### ISSUE TITLE
Update neco to run etcd v3.4

### ISSUE THREAD

**Issue by yokaze** [cybozu-go/neco#1594]
## What

Update severs for etcd v3.4.

## How

- Remove `--enable-v2` because it is no longer used

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@yokaze 
I don't this this is completed.  neco is running etcd 3.3 now.
