### ISSUE TITLE
Rook/Ceph: Study efficiency and possibility for placing RGW index in SSD

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1607]
## What

- The RGW index is placing in HDD, and we doubt that it could be slow.
- To improve performance, we consider to put RGW index in SSD.
  - Confirm that the RGW index is distributed across all OSD.
  - Confirm that the changes will really improve the performance.
  - It is possible to migrate RGW index to SSD from HDD without data loss.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#41
