### ISSUE TITLE
rook: reproduce the no-response from livenessProbe of RGW pod during bucket index resharding

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#1640]
We encounterd the failure of libvenessProbe of RGW pod during an bucket index resharding.

This problem has already reported in Rook.

https://github.com/rook/rook/issues/6304

In addition, an Ceph developer taught me this may be disappear in the new Ceph version.

https://github.com/rook/rook/issues/6304#issuecomment-853720944
```
> As I described in the previous post, "/swift/healthcheck/" would have a problem that it doesn't respons during bucket index resharding. Although I don't know the reason yet. Please let me if you know anything or know more proper endpoint.

Seems like a CPU starvation related performance issue during resharding.
There were improvements upstream to the reshard since the check time (sep 2020, the exact rgw version is not specified)
which potentially could improve CPU contention starvation situations.
may be worth our while to re-check with a current version.
```

To verify this hypothesis, we should reproduce this problem both in v15.2.8, the version which we hit this problem, and the latest v16.2.

**Comment by toshipp** [comment]
move to cybozu/csa#12
