### ISSUE TITLE
Submit feature request to kubernetes-sigs/hierarchical-namespaces about propagation of labels and annotations

### ISSUE THREAD

**Issue by akazs** [cybozu-go/neco#1642]
## What

Submit feature request to kubernetes-sigs/hierarchical-namespaces about propagation of labels and annotations

## How

1. Create an issue in kubernetes-sigs/hierarchical-namespaces
    1. Describe our use cases

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by binoue** [comment]
issue: https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/47
