### ISSUE TITLE
[Rook/Ceph] Stop auto resharding until resolve the problem of blocking access to RGW.

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1660]
## What

While Reshardning is running, access to the RGW will be blocked. This limitation is unacceptable, therefore, configure Reshardning not to run automatically.

## How

- Configure to stop dynamic-resharding.

ref https://github.com/cybozu-go/neco-apps/pull/1580/files

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#9
