### ISSUE TITLE
Rook/Ceph: Enable multiple MGR and RGW for ceph cluster.

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1662]
## What

- There is a MGR and RGW pod in each ceph cluster now.
- It is not good for availability of cluster.
- Enable multiple MGR and RGW in each cluster to get availability.

## How

- Configuration the number of MGR and RGW in cephcluster CRD.
- Confirm that the service will continue even if one of the pods in MGR or RGW stops.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#25
