### ISSUE TITLE
Rook/Ceph: Automatic graceful OSD down on node reboot or shutdown

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#1673]
## What

In the current implementation, when a Node shutsdown or restarts, it takes some time for the OSD to detect `down`.
When we intentionally shutdown a Node, we want the OSD to switch to the `down` state immediately.

upstream feature request:
https://github.com/rook/rook/issues/8209

## How

TBD

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#28
