### ISSUE TITLE
Squid 5.x

### ISSUE THREAD

**Issue by umezawatakeshi** [cybozu-go/neco#1771]
## What

Major version upgrade task to Squid 5.x

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@umezawatakeshi 
You might have been noticed but neco-apps (customer-egress) also contains Squid.
