### ISSUE TITLE
Add an alert that grafana is not available

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#1804]
## What

When the database is locked, grafana is healthy, but not available.

ref. https://github.com/grafana/grafana/issues/37438

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by umezawatakeshi** [comment]
The issue seems SQLite-specific. Our Grafana are now configurated to use MySQL and must not be affected.
