### ISSUE TITLE
NetworkPolicy

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#182]
## Description

Implement and enable Kubernetes NetworkPolicy in Neco data centers.

## Initiative / Motivation

NetworkPolicy is a critical feature to protect network services running in Neco data centers.
Specifically, we will run [teleport](https://gravitational.com/teleport/) or [Grafana](https://grafana.com/) on Kubernetes, and need to protect them.

## Scope and goal

* NetworkPolicy is implemented and available.
* Drop incoming packets by default using GlobalNetworkPolicy.

## Definition of ready

- [x] Initiatives and scopes are clearly stated.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people agree to make this ready.

**Comment by ymmt2005** [comment]
@zoetrope This epic is not ready yet.
To make it ready,
1. Prepare task issues.
2. Agree on the tasks and goals with more than three people.

**Comment by tapih** [comment]
> NetworkPolicy resources will no longer be served from extensions/v1beta1 in v1.16. Migrate use to the networking.k8s.io/v1 API, available since v1.8. Existing persisted data can be retrieved via the networking.k8s.io/v1 API.
