### ISSUE TITLE
Dynamic provisioner for local persistent volume

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#184]
## Description

Develop a dynamic provisioner for local persistent volumes.

## Initiative / Motivation

Local persistent volumes is a topology-aware abstraction of host-local storages in Kubernetes.
Although it became GA in Kubernetes 1.14, no dynamic provisioner for local persistent volume
is not included.  (FWIW, there is a [static provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner).)

We will use local persistent volumes to run Elasticsearch and MySQL clusters.
Because we have grouped NVMe SSDs in an LVM volume group for easier capacity management,
the dynamic provisioner for local persistent volume needs to create an LVM logical volume first.

The dynamic provisioner has to implement [CSI][].  The reasons are described in:
https://github.com/kubernetes/community/blob/master/sig-storage/volume-plugin-faq.md

Also. note that we need topology-aware dynamic volume provisioning.  As described in this
[official blog](https://kubernetes.io/blog/2018/10/11/topology-aware-volume-provisioning-in-kubernetes/), all we need to do is just set `volumeBindingMode` to `WaitForFirstConsumer`.

There are some existing implementations that may fulfill our requirements:

- https://github.com/wavezhang/k8s-csi-lvm
- https://github.com/mesosphere/csilvm
- https://github.com/embercsi/ember-csi

## Scope and goal

Prepare a dynamic provisioner for local persistent volume such that:

- Create an LVM logical volume for a new PV(C).
- Support all necessary volume attributes such as `mkfs` or `fsGroup`.
- Prefer to schedule to nodes having larger free spaces or less IO usage.
- Log PVC events as `Event` resources.
- Free unbound PV when a PVC is removed.
- Support volume resizing.
- Support topology-aware scheduling.
- Run some test application using local persistent volume (e.g. [M3DB][]).
- Be consistent with `lvmetad` running on host (or stop `lvmetad`).

## Definition of ready

- [x] Initiatives and scopes are clearly stated.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people agree to make this ready.

[CSI]: https://kubernetes-csi.github.io/docs/
[M3DB]: https://m3db.github.io/m3/m3db/

**Comment by zoetrope** [comment]
https://github.com/wavezhang/k8s-csi-lvm
https://github.com/mesosphere/csilvm
https://github.com/embercsi/ember-csi
