### ISSUE TITLE
Add new machine's information to sabakan

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#1854]
## What

This is a preliminary step to set up a new rack in our stage.

## How

- Add machine-types for the new machines
- Add new machines information with generate-sabakan-machines from a csv file that Network team is supposed to provide us.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by kmdkuk** [comment]
done in https://github.com/cybozu-private/neco-ops/issues/1426
