### ISSUE TITLE
Sandbox Grafana HA

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#1871]
## What

Make Grafana on sandbox high available like #1805.
~~Because when the pod is restarted, user's dashboard would be lost.~~ <- it won't be lost.
We use sandbox Grafana as development use (e.g. creating dashboards). So HA configuration is desirable.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by umezawatakeshi** [comment]
Because PDBs in `sandbox` NS are not completely honored during all-machines-reboot, we move sandbox Grafana to another NS.
