### ISSUE TITLE
Kubernetes networking design document including Cilium

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#1872]
## What

Share knowledge and design decisions related to Cilium.

## How

Add k8s networking design document that explains how Cilium works in our managed k8s cluster.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by terassyi** [comment]
Done.
