### ISSUE TITLE
Adjust CKE constraints after adding new rack

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#1880]
## What

We need to adjust CKE constraints to over-provision 1 rack of servers after adding new rack.

## How

Modify CKE constraints settings.

Current settings
```
$ ckecli constraints show
{
    "control-plane-count": 3,
    "minimum-workers": 68,
    "maximum-workers": 74,
    "maximum-unreachable-nodes-for-reboot": 0
}
```

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by kmdkuk** [comment]
done in https://github.com/cybozu-private/neco-ops/issues/1426
