### ISSUE TITLE
Storage version migrator

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#1883]
## What

[kube-storage-version-migrator](https://github.com/kubernetes-sigs/kube-storage-version-migrator) seems inactive.
It would be good to implement an operator to handle the storage versions of Kubernetes objects.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zoetrope** [comment]
CRD support
