### ISSUE TITLE
Kubernetes user management

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#190]
## Description

Make it possible to register Kubernetes users and define their roles and capabilities.

## Initiative / Motivation

We use [Teleport](https://gravitational.com/teleport/) to register users and map
GitHub teams to Kubernetes groups.  See #187 for this.

A general, non-administrator Neco user should have limited privilege for Kubernetes.
To name a few, a general user should:

- be able to edit resources in more than one namespaces.
- be able to publish network services by using IngressRoute or LoadBalancer Service.
- use resources limited by quota.
- *not* have access to Secrets in system namespaces such as `kube-system`.
- *not* be able to edit cluster-wide resources such as `Node`.
- *not* be able to edit the global security policies.
- *not* be able to use defined PodSecurityPolicies
- *not* be able to refer to defined ClusterRoles

## Scope and goal

- Define policies for general Neco users as a specification document
- Implement the policies

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people agree to make this ready.

**Comment by zoetrope** [comment]
https://gravitational.com/teleport/docs/kubernetes_ssh/

**Comment by mitsutaka** [comment]
From: https://kubernetes-security.info/

Tooling:

    Keycloak
    coreos/dex
    heptio/authenticator
    hashicorp/vault-plugin-auth-kubernetes
    appscode/guard
    cyberark/conjur
