### ISSUE TITLE
Enable LLDP on worker nodes

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#2060]
## What

LLDP functionalities on worker nodes don't seem to work correctly.
As a result, a network switch cannot identify the counterpart server on its port.

## How

Investigate and resolve.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zeroalphat** [comment]
LLDP is already enabled.
https://github.com/cybozu-go/neco/blob/release-2023.04.18-22452/ignitions/common/files/opt/sbin/setup-local-network#L25
