### ISSUE TITLE
Prevent deletion of container images required for startup

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#2086]
## What

When our data center is shut down for more than 72 hours, the container images required for startup may be deleted.

- https://github.com/cybozu-go/neco/blob/cf1fbc99aeb62d37e37c5c2c69f12e319622b6cd/debian/lib/systemd/system/docker-prune.service
- https://github.com/cybozu-go/neco/blob/cf1fbc99aeb62d37e37c5c2c69f12e319622b6cd/ignitions/common/systemd/docker-prune.service

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zeroalphat** [comment]
https://github.com/cybozu-go/neco/pull/2296
