### ISSUE TITLE
Include in the deb file the container images needed for startup

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#2087]
## What

Currently, boot server cannot connect to internet before start up Kubernetes cluster.
So we must include in the deb file the container images needed for startup.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zeroalphat** [comment]
Fix
https://github.com/cybozu-go/neco/pull/2200
