### ISSUE TITLE
Prepare self-hosted runners on GCP instances

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#2103]
## What

If the staging DC is down, neco-apps's CI which depend on stageing DC will not be available.
And we cannot release neco-apps.
So we need enable neco-apps's CI to run even if staging DC is down.

## How

- Update the `necogcp` command to run the GitHub Actions self-hosted runners on GCP instances.
- Write docs to setup the GCP runners in case of emergency.
- Set alerts to check GCP runners from running unnecessarily.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by aktech** [comment]
By the way: [cirun.io](https://cirun.io) does the same, without adding maintenance burden.
