### ISSUE TITLE
Cilium stops the LB IP announcement during the kube-apiserver outage

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#2148]
## What

Cilium stops the LB IP announcement during the kube-apiserver outage

## How

Test if the Cilium stops the announcement during the kube-apiserver outage, and if so, create an issue on the Cilium upstream and fix it.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by tkna** [comment]
作業スレ
[https://bozuman.cybozu.com/k/#/space/3801/thread/68598/4881308](https://bozuman.s.cybozu.com/k/#/space/3801/thread/68598/4881308)
[https://bozuman.cybozu.com/k/#/space/3801/thread/68598/4928984](https://bozuman.s.cybozu.com/k/#/space/3801/thread/68598/4928984)
[https://bozuman.cybozu.com/k/#/space/3801/thread/68598/5084940](https://bozuman.s.cybozu.com/k/#/space/3801/thread/68598/5084940)

作業中に発見した lastInteractionTime のバグ修正:
https://github.com/cilium/cilium/pull/31019

GithubのIssue
https://github.com/cilium/cilium/issues/31702

**Comment by tkna** [comment]
We decided to track this issue privately.
