### ISSUE TITLE
Monitor BPF map pressure

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#2166]
## What

If the BPF map is full, some features don't work. For example, when the policy map is full, the pod creation fails, and the network policy doesn't work correctly. Overflowing ct map causes connection breaks.

## How

Enable cilium_bpf_map_pressure and monitor it. Currently, cilium_bpf_map_pressure is not covering the CT map. So we need to find a way to monitor CT map pressure. Can we use cilium_datapath_conntrack_gc_entries instead?

See
https://github.com/cilium/cilium/issues/21508

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by terassyi** [comment]
This issue can be closed because of introducing [bpf_map_pressure_exporter](https://github.com/cybozu/neco-containers/tree/main/bpf-map-pressure-exporter).
