### ISSUE TITLE
Fix the diagram in README

### ISSUE THREAD

**Issue by utam0k** [cybozu-go/neco#2202]
**Describe the bug**

It seems that an important image in the README is corrupted.
![image](https://user-images.githubusercontent.com/13010913/215624662-a34ec97e-1eb5-4b20-b4bb-e4ddb3975303.png)

This picture came from this PR https://github.com/cybozu-go/neco/pull/1998.

**Environments**
- Browser: Chrome
- OS: Ubuntu 22.04

**To Reproduce**

Please check the README.md
https://github.com/cybozu-go/neco/blob/11d58bcf8f796aa5f1909e61637f5935a05cadf4/README.md#system-overview

**Expected behavior**

It shows a great architectural diagram.

**Additional context**

It may be better to use Mermaid which is able used in GitHub's Markdown instead of PlantUML.
https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
I will leave this to your judgment. This is just one option.

**Comment by yokaze** [comment]
@utam0k 
Thanks for the report!
I checked the previous and current URLs of PlantUML and confirmed that both are corrupted.
Possibly the upstream changed something, and it affected the rendering of the image?
We need to fix the script, which will take some time.

**Comment by utam0k** [comment]
@yokaze Thanks for your quick response! I am looking forward seeing it.

**Comment by yokaze** [comment]
@utam0k 
Possibly because of the asynchronous communication, but @zoetrope has fixed it immediately. Thank you for the offer 🙇‍♂️
