### ISSUE TITLE
Configure GitHub webhook notifications to ArgoCD to avoid a delay of scanning for repository change

### ISSUE THREAD

**Issue by takara9** [cybozu-go/neco#2283]
## What

A detection of the repository chages takes long time at ArgoCD.  Software developers must wait a apply of repository changes for production environment without notification. 

## How

To solve this issue, reconfigure that ArgoCD can be recieve a change event by webhook from GitHub.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by masa213f** [comment]
done
