### ISSUE TITLE
some containers used by neco do not be created properly

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#231]
## What

As a result of the following EPIC, some regressions, some containers used by neco do not be
created properly, happen.

https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/neco/194

## How

Fix problematic container's Dockerfiles. First, CKE container should create /usr/local/cke before
copying CKE binary files to this directory.

We should confirm whether similar problems exist or not in made-by-cybozu containers like
sabakan and coil. If there are any problem, we should also fix them.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@satoru-takeuchi 
Please check items in check list.

**Comment by satoru-takeuchi** [comment]
Oops, sorry. Done.
