### ISSUE TITLE
Increase the number of control planes to 5

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#2355]
## What

Increase the number of control planes to 5

## How

Change the following parameter:
https://github.com/cybozu-go/cke/blob/main/docs/constraints.md?plain=1#L11

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by takara9** [comment]
完了
