### ISSUE TITLE
[neco] Create sabakan-state-setter

### ISSUE THREAD

**Issue by mitsutaka** [cybozu-go/neco#247]
## What

Implement a new command `sabakan-state-setter` in cybozu-go/neco.
This command will be executed by `systemd.timer`.

## How

Decode state by condition as follows:

- Set `Healthy`
  - serf status is `alive`.
  - serf tags `systemd-units-failed` is set and has no errors.
  - All of later mentioned machine peripherals are healthy.
- Set `Unreachable`
  - serf status is `failed`, `left` or machine is not yet as a serf member. It is the same as that `sabakan-state-setter` can not access monitor-hw metrics.
- Set `Unhealthy`
  - serf status is `alive`.
  - At least one of them matches:
    - serf tags `systemd-units-failed` is not set or has errors.
    - `sabakan-state-setter` can not retrieve monitor-hw metrics.
    - At least one of later mentioned machine peripherals is unhealthy.
- Nothing to set machine state
  - `sabakan-state-setter` can not access to `serf.service` of the same boot server.

### Target machine peripherals

- CPU
- Memory
- Storage controllers
- NVMe SSD
- Dell BOSS

Unit test for `sabakan-state-setter` prepare mock server to emulate monitor-hw metrics.

Remove sabakan-serf-handler.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Remove sabakan-serf-handler.

**Comment by mitsutaka** [comment]
Remaining task:
- Add machine-type, remove os-version of the sabakan machine labels on stage0 by the operation.
- Support configuration file to define metrics list for decision machine state. It can distinguish an unhealthy condition using monitor-hw metrics.
