### ISSUE TITLE
Deploy and Configure External DNS

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#255]
## What

Deploy External DNS on Kubernetes cluster.

## How

* Create External-DNS container image
* Add manifests for above container to neco-ops
* Add NS record of CloudDNS to google-domains
* Add a credential of CloudDNS to CircleCI job
* Add test scenarios for External-DNS
* Write documentation of the procedure to add a credential of CloudDNS to staging

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Notify developers of necessary actions

**Comment by mitsutaka** [comment]
> Add test scenarios for External-DNS
Test only DNS resolving. Other access routing test cases will be implemented by #256
