### ISSUE TITLE
Installation issues for dctest.

### ISSUE THREAD

**Issue by hhnugm** [cybozu-go/neco#2566]
OS info Linux A100-test 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Docker version 26.1.3, build b72abbb
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:01:00.0 Off |                    0 |
| N/A   33C    P0             55W /  400W |      13MiB /  39936MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-SXM4-40GB          Off |   00000000:41:00.0 Off |                    0 |
| N/A   32C    P0             54W /  400W |      13MiB /  39936MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100-SXM4-40GB          Off |   00000000:81:00.0 Off |                    0 |
| N/A   28C    P0             51W /  400W |      13MiB /  39936MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100-SXM4-40GB          Off |   00000000:C1:00.0 Off |                    0 |
| N/A   26C    P0             52W /  400W |      13MiB /  39936MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A    147955      G   /usr/lib/xorg/Xorg                              4MiB |
|    1   N/A  N/A    147955      G   /usr/lib/xorg/Xorg                              4MiB |
|    2   N/A  N/A    147955      G   /usr/lib/xorg/Xorg                              4MiB |
|    3   N/A  N/A    147955      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+

[makesetuperror.txt](https://github.com/user-attachments/files/15507579/makesetuperror.txt)

There is a single-node A100GPU server that installs these steps below successfully.

$ sudo curl -o /etc/apt/keyrings/docker-key.asc -fsSL https://download.docker.com/linux/ubuntu/gpg 
$ echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-key.asc] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
$ sudo apt update
$ sudo apt install -y build-essential systemd-container lldpd qemu qemu-kvm socat picocom swtpm cloud-utils bird2 squid chrony dnsmasq jq freeipmi-tools unzip skopeo fakeroot docker-ce docker-ce-cli containerd.io
$ wget https://github.com/qemu/qemu/raw/master/pc-bios/bios.bin
$ wget https://github.com/qemu/qemu/raw/master/pc-bios/bios-256k.bin
$ sudo install -m 0644 -b bios.bin bios-256k.bin /usr/share/seabios/
$ wget https://github.com/cybozu-go/placemat/releases/download/v2.4.0/placemat2_2.4.0_amd64.deb
$ sudo dpkg -i ./placemat2_2.4.0_amd64.deb
$ git clone https://github.com/cybozu-go/neco
$ cd neco/dctest

make setup happened error 100 as an attachment.
can not make placemat

Question 1: How do I fix it? 

Question 2: How many nodes should I prepare for the minimum virtual dctest? Currently only set up one node.

Question 3: Can I have a minimum virtual dctest topology?

Question 4: How many necessary apt toolkits should be installed?

Many Thanks.

**Comment by morimoto-cybozu** [comment]
@hhnugm 
Hi, thank you for trying Neco!
The error message below indicates that your server is configured to refer to an unavailable APT server.
The repository `apt.kubernetes.io` has been [deprecated](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/).

```
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.
```

I'm afraid we may not keep the "Virtual data center" section in README up-to-date.
We run the virtual data center tests on GCP VMs.
It would be helpful to read `.circleci/config.yml` for running the tests in the same manner.

The tests require a somewhat large-scale server.
For example, we use a `n1-highmem-32` GCE instance, which is equipped with 32 vCPUs and 208 GB memory.

If you are interested in the virtual data center rather than Neco, you might want to check out [placemat](https://github.com/cybozu-go/placemat).
