### ISSUE TITLE
Device count rules for sabakan-state-setter

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#273]
## What

`sabakan-state-setter` should be able to have rules to test the expected or minimal
number of healthy devices.

- For NVMe SSD, we want to define the exact number of healthy devices for each machine type.
  (regardless of in which slots they are installed)
- For HDD, we want to define the minimum number of healthy devices for each machine type.

As to [BOSS](https://i.dell.com/sites/doccontent/shared-content/data-sheets/en/Documents/Dell-PowerEdge-Boot-Optimized-Storage-Solution.pdf), we want to check the controller existence and RAID status, which can be defined with the current implementation, right?
If not, enhance the rule implementation.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
ログが全然出てないのも何とかする
