### ISSUE TITLE
[sabakan-state-setter] fix the race condition of the state setting process

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#296]
## What

Current implementation works as follows when setting the state of a machine.

1. Decide the next state
2. Request sabakan to change the state

Here step 1 and step 2 are not atomic. So if multiple sabakan-state-setter run in parallel,
the machine state would get incorrect. For example, if sakaban-state-setter A and B run in parallel,
it happens as follows.

1. A: step1
2. B: step1
3. B: step2
4. A: step2

## How

TBD

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
By design.
