### ISSUE TITLE
Get rid of podman

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#300]
## Description

We should use Docker instead of podman to build images for testing.
Install Docker onto the base image of host-vm and use it.

## Initiative / Motivation

`podman build` often degrades.  Using Docker will stabilize our development process.
One concern is that placemat may malfunction with Docker networking.

## Scope and goal

Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning.

- Prepare Docker on host-vm
- Use docker to build images for testing.
- Finally, purge podman.

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people agree on making this ready.

**Comment by mitsutaka** [comment]
> Prepare Docker on host-vm
Done by [necogcp] hardcode the base image name of vmx-enabled image #318

> Use docker to build images for testing.
Done by Get rid of podman #338

> Finally, purge podman.
Done by Get rid of podman #338
