### ISSUE TITLE
Create teleport containers

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#363]
## What

As teleport will run as containers, we need to create teleport container images.

## How

Add Dockerfile to create teleport containers to `neco-container` repository.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@binoue Please fill the ckeckboxes.
