### ISSUE TITLE
[neco][neco-apps] Clean up old labels

### ISSUE THREAD

**Issue by dulltz** [cybozu-go/neco#382]
## What

Old name labels (`name`, `k8s-app`) are still remaining in somewhere to support backward compatibility. i.e. https://github.com/cybozu-go/neco-apps/blob/bdf2d769668a48db42c94678c849b11e23a25a20/network-policy/base/policies/internet-egress.yaml#L34

It is unnecessary after updating is succeeded.

## How

Remove them

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by binoue** [comment]
Checked:
- neco-containers
- cke
- coil
- contour-plus
- neco
- neco-apps
- topolvm
- sabakan
- placemat

Note:
`cke` is still using `k8s-app` label which is not recommended, because of the following reasons.
- `sonobuoy` needs the label
- referenced yamls are using the label
