### ISSUE TITLE
[neco][neco-updater] Send an update successful notification to slack if not yet

### ISSUE THREAD

**Issue by mitsutaka** [cybozu-go/neco#385]
## What

When leader election of the `neco-updater` is delayed, a new leader does not send a successful notification. According to the boot server log:

- 01:52:12 boot-1 `neco-updater` is leader. however boot-1 network had a problem.
- 02:06:54 boot-1 Restart `neco-updater` after solving the network problem.
- 02:07:27 boot-1 `neco-worker` finished update process. 
- 02:07:32 boot-0,2 `neco-worker` finished update process.
- 02:07:40 boot-0 `neco-updater` is leader now. however,  it does not send a notification and the next action is `wait-for-info`. Because if all worker nodes' update process is completed, the following code is skipped.

```go
	if !neco.UpdateCompleted(ss.Request.Version, ss.Request.Servers, ss.Statuses) {
		if time.Now().Sub(ss.Request.StartedAt) > timeout {
			return ActionStop, nil
		}
		return ActionWaitWorkers, nil
	}
```

`ActionWaitWorkers` sends a notification.

## How

- `neco-updater` leader checks with some flags or an etcd key whether sending an update successful notification is already done or not.
- If it's not yet, send a notification.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
This problem has not been observed for a while.  Closing.
