### ISSUE TITLE
[neco-apps] node becomes unstable after rebooted in TopoLVM test

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#408]
## What

TopoLVM test reboots a node to check persistency of data.
After a node is rebooted, the node stays NotReady in `kubect get node` for several minutes.
CKE fails in `kubelet-bootstrap`'s `retaint-before-kubelet-boot` in the meantime.

## How

TBD

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
This is not an issue/task, rather a bug.
