### ISSUE TITLE
[etcd] The key is not deleted when the bound lease expires

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#417]
**Describe the bug**

The key in etcd is not deleted when the bound lease expires.

Precise conditions for reproduction are not clear.
After we ran cke-etcd in neco's staging env for a while, with adding/removing etcd cluster members, we found that the keys of `/registry/masterleases/<API server IP address>` for old API servers were not deleted.

There remained many expired leases seen by `etcdctl lease list` and `etcdctl lease timetolive`.
This may or may not be by design.

Note that the [improvement of sabakan-state-setter](https://github.com/cybozu-go/neco/issues/398) will decrease frequency of addition/removal of etcd cluster members, and the [improvement of CKE](https://github.com/cybozu-go/neco/issues/397) will completely stop the use of `/registry/masterleases/<API server IP address>`.

**Environments**

- Version: etcd 3.3.12.2
- OS: Ubuntu 18.04

**To Reproduce**

Steps to reproduce the behavior: not identified yet

**Expected behavior**

The key in etcd is deleted when the bound lease expires.

**Comment by ymmt2005** [comment]
We have not seen this issue for some time.
