### ISSUE TITLE
CKE 1.15

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#433]
## What

Update CKE for Kubernetes 1.15.

## How

- Use hyperkube and CoreDNS for Kubernetes 1.15, and apply the necessary fixes.
- Use sigs.k8s.io/yaml
- Update `k8s.io/client-go` to `@kubernetes-1.15.2`.
- Delete `--allow-privileged=` option from kubelet
- Enable `--ipvs-strict-arp` option with kube-proxy for MetalLB 
- Drop support for user-defined policies in extensions/v1beta1 by stating it in the changelog
- Update `images.go` to point the newest images of etcd, pause, and so on.
- Update containerd to 1.2.7
- Update Makefile to use `kubectl` 1.15
- Update `k8s.io/client-go` for machines-endpoints to `kubernetes-1.15.2` as follows:
    ```
    go get k8s.io/client-go@kubernetes-1.15.2
    go mod tidy
    go mod vendor
    git add -f vendor
    ```

Note: 
The following content is already discussed in CKE 1.14 ( https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/neco/238 )

`kube-proxy` in 1.15 does not clear existing rules at startup.
To clean up rules, `kube-proxy --cleanup` need to be called; when the proxy mode is changed e.g. from `iptables` to `ipvs`, cleanup is a must.

That said, CKE runs `kube-proxy` explicitly with `--proxy-mode=ipvs` (https://github.com/cybozu-go/cke/blob/6e117dae02e2d7da8c11a46102b7ec7ae24b3047/op/k8s/proxy_boot.go#L101).
So we do not call `kube-proxy --cleanup` for now.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by binoue** [comment]
As stated in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#release, rename contro-manager, proxy, scheduler, controller-manager, and apiserver to kube-proxy, kube-scheduler,  kube-controller-manager, and kube-apiserver.
