### ISSUE TITLE
ArgoCD 1.2.1

### ISSUE THREAD

**Issue by dulltz** [cybozu-go/neco#445]
## What

Update Argo CD to 1.2.1 and enable self-healing feature.

Self-fealing automatically recovers from out-of-sync status of the
once synchronized applications.

## How

- Upgrade ArgoCD to 1.2 because self-healing feature is supported in this version
- Modify argocd configurations

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by mitsutaka** [comment]
Canceled https://github.com/cybozu-go/neco-apps/pull/110#issuecomment-527711028

**Comment by mitsutaka** [comment]
Move to Icebox, we can apply after fix Argo CD's bug.
