### ISSUE TITLE
sabakan-state-setter: test state transition with considering grace period

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#456]
## What

We should test whether the state transition to `Unhealthy` with considering grace period works
well or not.

Currently, we just test whether sabakan-state-setter changes machine state to expected one
at one point of time as follows.

https://github.com/cybozu-go/neco/blob/334d488891f2fe81007240a0d1cfa31750d45c4f/pkg/sabakan-state-setter/controller_test.go#L135

If we call this kind of test `stateless test`,  we should also add `stateful test` as follows.

- step1: the machine state is not changed when the machine is regarded as `Unhealthy` at the first time.
- step2: the machine state is not changed during the machine have been regarded as `Unhealthy` shorter than the grace period
- step3: the machine state is changed to `Unhealthy` once after the machine has been regarded as `Unhealthy` longer than or equal to the grace period.

### Background

After the following PR, sabakan-state-setter have `grace-period` parameter.

https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/neco/420

Before this, we intended to implement this feature by the following PR.

https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/neco/400

However, it hasn't worked completely. The root cause is that sabakan-state-setter clear the internal
state, what machines are regarded as `Unhealthy` from when,  on each interval. Since this kind of
problem can't be detected by stateless-test, we should also add stateful-test.

## How

TBD

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Done in https://github.com/cybozu-go/neco/pull/470/files
