### ISSUE TITLE
[neco][ignition] Chicken or the egg problem between {exec-,}setup-hw.service and sabakan-cryptsetup

### ISSUE THREAD

**Issue by mitsutaka** [cybozu-go/neco#466]
## What

In the factory configuration servers, TPM is disabled e.g. machine-type `r740xd-ss-2`.
To use `sabakan-cryptsetup` with TPM, TPM must be enabled before initial encryption.
OTOH, `setup-hw.service` container requires a persistent volume in the server's storage and must be initialized by `sabakan-cryptsetup`.

## How

Consider systemd execution order.

1. Run `setup-hw.service` and use some tmpfs space for running its container.
2. Run `exec-setup-hw.service`, if reboot is required, it should be restarted automatically to prevent running `sabakan-cryptsetup` without TPM on the TPM2.0 supported servers.
3. Run `sabakan-cryptsetup` as usual.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Done in https://github.com/cybozu-go/sabakan/pull/169
