### ISSUE TITLE
Monitoring Prometheus on k8s by Prometheus on boot server

### ISSUE THREAD

**Issue by dulltz** [cybozu-go/neco#481]
## What

We have no monitoring system for the monitoring system on k8s,
so we have no way to know if the Prometheus on k8s is alive or not.

## How

- Deploy Prometheus and Alertmanager on boot server to monitor the Prometheus on k8s.
- Add watchdog rule to know when the monitoring stack is dead.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
We have two VictoriaMetrics monitoring systems now.
