### ISSUE TITLE
[neco-apps] Replace bases field in kustomization.yaml

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#507]
## What

The `bases` field in `kustomization.yaml` is deprecated from Kustomize v3.1.0.
`neco-apps` can use Kustomize v3.1.0(ArgoCD 1.2.0-rc2) now. Manage the deprecation.

## How

Replace `bases` field to `resources` filed.

https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v2.1.0.md#field-changes--deprecations

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
https://github.com/cybozu-go/neco-apps/pull/705
