### ISSUE TITLE
Improve Webhook configuration for rebooting all workers

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#515]
## What

When all workers are rebooted, some cluster resources cannot be edited, 
because webhook server is down.
So we need to exclude cluster resources from the target of webhook.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Closing because this will not affect our environment.

1. Restarting all nodes will preserve all resources in apiserver including Pods.
2. The incident happened because of a buggy behavior of CKE.
