### ISSUE TITLE
[neco-apps] test network policies without fake labels

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#537]
## What

`test/network-policy_test.go` tests network policies.
It uses fake labels `app.kubernetes.io/name=...` for Ubuntu pods to test some policies because (1) the original target pods of the policies do not have enough commands to test network accessibility, and (2) the target pods are determined according to labels.
These labels are used, however, also for determining members of services, and may lead to confusion.
Fix this.

## How

Attach a sidecar Ubuntu container?

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@tapih 
Is this already resolved by you?
IIRC, you changed the test by adding a sidecar container.

**Comment by ymmt2005** [comment]
Cc: @morimoto-cybozu

**Comment by morimoto-cybozu** [comment]
@ymmt2005 
Exactly.  https://github.com/cybozu-go/neco-apps/pull/159 fixes this.
We have no "kubectl label pod" for test now.

**Comment by ymmt2005** [comment]
Thanks.  Closed.
