### ISSUE TITLE
coil-installer does not clean up the host-side veth

### ISSUE THREAD

**Issue by dulltz** [cybozu-go/neco#540]
**Describe the bug**

coil-installer cannot be retried on the same pod,
because coil-installer does not clean up the host-side veth.

The name of veth is decided by Pod name deterministically to adopt the naming rule of calico.

**Environments**
- neco release-2019.09.04-6385

**To Reproduce**
1. Construct neco k8s cluster.
1. Choose one of the coil-node pods, and get the veth name on the node which contains the pod.
1. Delete the coil-node pod.
1. Enter the node, then confirm the veth exists by `$ ip l`.

**Additional context**

You can get the veth name from the pod name by the following code.

```go
package main

import (
	"crypto/sha1"
	"encoding/hex"
	"fmt"
)

func main() {
	h := sha1.New()
	h.Write([]byte(fmt.Sprintf("%s.%s", "topolvm-system", "csi-topolvm-node-tnjfp")))
	fmt.Printf("%s%s", "veth", hex.EncodeToString(h.Sum(nil))[:11])
}

```

**Comment by ymmt2005** [comment]
move to coil repository.
