### ISSUE TITLE
add LoadBalancer type service for argocd-server

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#558]
## What

We want to run `argocd` command from an operational terminal.

## How

Add a LoadBalancer type service and Certificate for argocd as well as teleport.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Resolved in https://github.com/cybozu-go/neco-apps/pull/169
