### ISSUE TITLE
neco-apps test using local manifests

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#560]
## What

dctest and kindtest for neco-apps are using manifests on a GitHub repository.
For development and debugging, I want to use modified manifests on local.

## How

We will use `argocd app sync --local` command for the tests.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by yokaze** [comment]
This task is already completed.
https://github.com/cybozu-go/neco-apps/blob/422cbc688e8c5f036e0176137971cee203828f30/test/setup_test.go#L406
