### ISSUE TITLE
Monitor teleport availability

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#582]
## What

Monitor teleport availability externally and store metrics in Prometheus.

## How

add `--diag-addr=http://127.0.0.1:3434` option.

See the following article.
https://engineering.bitnami.com/articles/implementing-slos-using-prometheus.html

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by kfyharukz** [comment]
This issue will be done in #722 .
