### ISSUE TITLE
Dashboard for API server latency

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#613]
## What

To debug why API server responds slowly, prepare a Grafana dashboard
to break down requests, especially with requests to admission webhooks.

Background: validating webhook installed by gatekeeper slowed down
overall API server requests.
https://bozuman.cybozu.com/k/#/space/3801/thread/25931/2104679/2689821

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by kfyharukz** [comment]
This issue was done in #564.
