### ISSUE TITLE
Enable debugging when CoreOS fails to boot

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#624]
## What

**Only for GCP/test environment**

We have observed sometimes setup-var.service does not complete during CoreOS boot process.
To investigate the root cause, allow humans to log in as root when this happens.

## How

- Add a login password for the `root` user of dctest CoreOS nodes
- Stop infinite loop of `setup-var` If the waiting time exceeds 20 minutes(=Timeout by CircleCI)

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by dulltz** [comment]
Check if we can log in even if setup-ver.service fails.
