### ISSUE TITLE
ceph-volume: allow non-physical devices in `lvm prepare --data <device path>`

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#627]
## What

`ceph-volume lvm prepare --data <device path>` only accepts physical block
devices and partitions.

It will be convenient to support other kinds of devices.

Possible use cases are as follows:
- With dm-flakey, we can simulate the failure of devices in testing.
- With dm-crypt, we can use encrypted devices with a variety of
encryption methods.

## How

Currently, we're trying to resolve this problem by fixing Ceph.

Here is the Ceph issue.
https://tracker.ceph.com/issues/42502

In addition, here is the PR.
https://github.com/ceph/ceph/pull/31205

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by satoru-takeuchi** [comment]
one of Ceph community member prefers to enable each device type one by one,
instead of enabling all at once. We closed this ticket since its scope is too wide.

**Comment by ymmt2005** [comment]
Canceled
