### ISSUE TITLE
[neco-apps] teleport locality is incorrect

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#641]
**Describe the bug**
As shown in the log below, locality is set as `cybozu`

- log
INFO [CA]        Generating TLS certificate {0x3339ea0 0xc001647390 CN=xxxxx,O=admin,POSTALCODE=null,STREET=,L=cybozu 2019-10-31 17:16:21.578351235 +0000 UTC []}. common_name:xxxxx dns_names:[] locality:[cybozu] not_after:2019-10-31 17:16:21.578351235 +0000 UTC org:[admin] org_unit:[] tlsca/ca.go:203

**Environments**
- Version: 18.04
- OS: Ubuntu

**To Reproduce**
1. Create neco-apps environment
2. run this command and check the value of locality
    - `kubectl logs teleport-auth-0  -n teleport | grep "Generating TLS certificate"`

**Expected behavior**
The value of locality should be empty

**Additional context**

**Comment by ymmt2005** [comment]
> The value of locality should be set as Tokyo

Really?  I think it can be left empty.

**Comment by ymmt2005** [comment]
./60-persistent-storage.rules:KERNEL=="mmcblk[0-9]boot[0-9]", ENV{DEVTYPE}=="disk", ENV{ID_PATH}=="?*", SYMLINK+="disk/by-path/$env{ID_PATH}-boot%n"

**Comment by ymmt2005** [comment]
https://github.com/gravitational/teleport/pull/2187
