### ISSUE TITLE
Allow neco-developer to access service in ingress namespace

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#659]
## What

neco-developer needs access to service in ingress namespace to get IP address of ingress. 

## How

Add a permission to [https://github.com/cybozu-go/neco-apps/blob/master/team-management/base/common/clusterrole.yaml](ClusterRole).

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
unnecessary.
