### ISSUE TITLE
Get rid of fsGroup

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#660]
## What

`fsGroup` can cause performance problem for volumes containing a lot of files
because it recursively traverses the filesystem and changes the file group.

Specifically, following `fsGroup` should be removed from neco-apps.

```
monitoring/base/grafana/statefulset.yaml:        fsGroup: 10000
monitoring/base/prometheus/statefulset.yaml:        fsGroup: 10000
teleport/base/statefulset.yaml:        fsGroup: 10000
```

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by masa213f** [comment]
fsGroup are removed by the following PR.
https://github.com/cybozu-go/neco-apps/pull/717
