### ISSUE TITLE
[teleport] Prevent expiration of TLS certificate of teleport-proxy

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#667]
## What

Currently, teleport-proxy does not reload its updated secret.
Therefore, at some point, teleport-proxy uses outdated certificate and users are unable to login via teleport.

This should be solved.

[Related conversation is here](https://bozuman.cybozu.com/k/#/space/3801/thread/27736/2166828/2808219)

## How

Add [this logic](https://github.com/cybozu/neco-containers/blob/e0c8554a6ac1b9afa54b8d09878e0c9cdb2f097e/bmc-reverse-proxy/pkg/bmc-reverse-proxy/main.go#L171-L192) and make a pull request to the upstream

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by tapih** [comment]
The PR to the upstream is below:
https://github.com/gravitational/teleport/pull/3272
