### ISSUE TITLE
[neco-wiki] Update the periodical repair server processes

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#670]
## What

The periodical repair server processes should be changed to register all not healthy servers in the processes.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by dulltz** [comment]
It is necessary additional check for NIC fimware version
```console
$ ethtool -i <nic-name>
```
