### ISSUE TITLE
k8s KEP: comment on a KEP to support storage capacity constraints for pod scheduling

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#671]
## What

When we introduce TopoLVM in sig-storage slack, we were asked to comment on a KEP that is to support storage capacity constraints for pod scheduling. If this KEP is accepted, TopoLVM can implement capacity-aware pod scheduling in a generic way and can be simplified very much. It's nice to share our knowledge. 

https://github.com/kubernetes/enhancements/pull/1353

## How

Read this KEP and the corresponding discussion, and comment on this KEP from the TopoLVM developer's point of view.

sig-storage slack's thread.
https://app.slack.com/client/T09NY5SBT/C09QZFCE5/thread/C09QZFCE5-1575360606.458400

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
These KEPs become implementable.
