### ISSUE TITLE
Check the release note of Kubernetes 1.16

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#678]
## What

To conform to kubernetes 1.16, check the release note of this version.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md

## How

Read it and pick the necessary actions.
Necessary actions should be listed as comments for this issue.

e.g. https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/neco/236

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by binoue** [comment]
Continued deprecation of extensions/v1beta1, apps/v1beta1, and apps/v1beta2 APIs; these extensions will be retired in 1.16!

**Comment by binoue** [comment]
Notable changes. confirm they are not used 

- All resources under apps/v1beta1 and apps/v1beta2 - use apps/v1 instead
- daemonsets, deployments, replicasets resources under extensions/v1beta1 - use apps/v1 instead
- networkpolicies resources under extensions/v1beta1 - use networking.k8s.io/v1 instead
- podsecuritypolicies resources under extensions/v1beta1 - use policy/v1beta1 instead

**Comment by binoue** [comment]
topolvm is using apiextensions.k8s.io/v1beta1 for its CRD

> The apiextensions.k8s.io/v1beta1 version of CustomResourceDefinition is deprecated and will no longer be served in v1.19. Use apiextensions.k8s.io/v1 instead

**Comment by binoue** [comment]
neco-apps and so on

> The admissionregistration.k8s.io/v1beta1 versions of MutatingWebhookConfiguration and ValidatingWebhookConfiguration are deprecated and will no longer be served in v1.19. Use admissionregistration.k8s.io/v1 instead.

**Comment by binoue** [comment]
Add apiserver_boot.go in neco
> The GA PodPriority feature gate is now on by default and cannot be disabled.

**Comment by binoue** [comment]
Use readiness probe for core-dns
> The CoreDNS Deployment now checks readiness via the ready plugin.

**Comment by masa213f** [comment]
Rreplace `cadvaisor` metric label.
https://github.com/cybozu-go/neco-apps/blob/1e92ea7b91d67c2bbfb67bcfc8d96cb85b5c6741/monitoring/base/grafana/dashboards/kubernetes_cluster.json#L1220


https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#changelog-since-v1160-alpha3
> Removed cadvisor metric labels pod_name and container_name to match instrumentation guidelines. (#80376, @ehashman)
> Action required: any Prometheus queries that match pod_name and container_name labels (e.g. cadvisor or kubelet probe metrics) must be updated to use pod and container instead.

**Comment by binoue** [comment]
neco-admission, topolvm webhook can omit failurePolicy
> failurePolicy default changed from Ignore to Fail for v1

**Comment by masa213f** [comment]
We may delete the following RBAC.
Because `daemonsets`, `deployments`, `replicasets` resources under `extensions` are not serverd.

https://github.com/cybozu-go/neco-apps/blob/89960378184123e4e06ab1b5c146565a8b445fe1/monitoring/base/kube-state-metrics/role.yaml#L21-L25

*OR* add the following APIServer flags for `kube-state-metrics`.
- `extensions/v1beta1/daemonsets=true`
- `extensions/v1beta1/deployments=true`
- `extensions/v1beta1/replicasets=true`

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals
> The following APIs are no longer served by default:
> daemonsets, deployments, replicasets resources under extensions/v1beta1 - use apps/v1 instead

**Comment by masa213f** [comment]
We may replace the following RBAC.
Because `podsecuritypolicies` resources under `extensions` are not served.

https://github.com/cybozu-go/neco-apps/blob/89960378184123e4e06ab1b5c146565a8b445fe1/metallb/base/role.yaml#L51-L58

**Comment by masa213f** [comment]
`applications` CRD provided by ArgoCD has `metadata.initializers`.
https://github.com/cybozu-go/neco-apps/blob/668923606216221456240c396bc674b8f5860316/argocd/base/crd.yaml#L103-L114

> The alpha `metadata.initializers` field, deprecated in 1.13, has been removed.

**Comment by binoue** [comment]
CRD fields changed. At least topolvm CRDs must be modified

- Use of the new default feature in validation schemas is limited to v1
- spec.scope is no longer defaulted to Namespaced and must be explicitly specified
- spec.version is removed; use spec.versions instead
- spec.validation is removed; use spec.versions[*].schema instead
- spec.subresources is removed; use spec.versions[*].subresources instead
- spec.additionalPrinterColumns is removed; use spec.versions[*].additionalPrinterColumns instead
- spec.conversion.webhookClientConfig is moved to spec.conversion.webhook.clientConfig
- spec.conversion.conversionReviewVersions is moved to spec.conversion.webhook.conversionReviewVersions
- spec.versions[*].schema.openAPIV3Schema is now required when creating v1 CustomResourceDefinitions
- spec.preserveUnknownFields: true is disallowed when creating v1 CustomResourceDefinitions; it must be specified within schema definitions as x-kubernetes-preserve-unknown-fields: true
In additionalPrinterColumns items, the JSONPath field was renamed to jsonPath (fixes https://github.com/kubernetes/kubernetes/issues/66531)

**Comment by binoue** [comment]
new metrics
added an new Prometheus counter metric "sync_proxy_rules_iptables_restore_failures_total" for kube-proxy iptables-restore failures (both ipvs and iptables modes)

**Comment by dulltz** [comment]
Delete `scheduler.alpha.kubernetes.io/critical-pod` annotation from here https://github.com/cybozu-go/cke/blob/557d53f10e3265c586045bbd0a857b6e5b572812/example/calico.yaml

**Comment by binoue** [comment]
Better to add `--shutdown-delay-duration ` to kube-apiserver?

> Add --shutdown-delay-duration to kube-apiserver in order to delay a graceful shutdown. /healthz will keep returning success during this time and requests are normally served, but /readyz will return faillure immediately. This delay can be used to allow the SDN to update iptables on all nodes and stop sending traffic.

**Comment by binoue** [comment]
[EvenPodsSpread](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) should be true now or later?

> Pod spread constraints have been added in alpha. You can use these constraints to control how Pods are spread across the cluster among failure-domains.
