### ISSUE TITLE
Rook: support OSD on non-PVC LV

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#689]
## What

OSD on LV-backed feature will be available in Rook v1.2. In addition, supporting OSD on non-PVC LV is also nice since it's needed by other people.

issue:
https://github.com/rook/rook/issues/2047

Suggestion to implement OSD on non-PVC LV in the issue for OSD on LV-backed PVC:
https://github.com/rook/rook/pull/4219#discussion_r345891844

## How

Depending on the discussion in the task of this feature request.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@satoru-takeuchi 
Do you still want to try this?

**Comment by satoru-takeuchi** [comment]
No, I don't have a strong motivation in this feature. I close this issue.

There are two reasons. First, there is an alternative way, PVC-based cluster with static-provisioned PV backed by Logical volume. Second, Rook community will implement raw mode OSD in host-based cluster near the future. Then this function won't be needed anymore.
