### ISSUE TITLE
[cke] Prevent kube-proxy from clearing its IPVS / iptables rules after restarting

### ISSUE THREAD

**Issue by tapih** [cybozu-go/neco#692]
## What

kube-proxy (from 1.14?) clears its IPVS / iptables rules after restarting.
CKE should suppress the clearance to avoid temporal access failure.

## How

TBD

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by masa213f** [comment]
Canceled.  Clearing IPVS / iptables rules are suppressed from k8s v1.14.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#changelog-since-v1140

>kube-proxy no longer automatically cleans up network rules created by running kube-proxy in other modes. If you are switching the mode that kube-proxy is in running in (EG: iptables to IPVS), you will need to run kube-proxy --cleanup, or restart the worker node (recommended) before restarting kube-proxy. (#76109, @vllry)

> - If you are not switching kube-proxy between different modes, this change should not require any action.
> - This fixes a bug where restarting the iptables proxier can cause connections to fail (https://github.com/kubernetes/kubernetes/issues/75360).
