### ISSUE TITLE
Renew Kubernetes Certification of CKE

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#693]
## What

Renew CKCF Kubernetes Certification for CKE v1.16.

Ref: For 1.15, this was the PR: https://github.com/cncf/k8s-conformance/pull/702

Note that sonobuoy now needs a special flag for conformance testing.
```console
$ sonobuoy run --mode=certified-conformance
```

## How

1. Add `--mode` flag to sonobuoy
2. Release CKE 1.16.0
3. Submit test results attached in GitHub release to github.com/cncf/k8s-conformance

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
https://github.com/cncf/k8s-conformance/pull/821
