### ISSUE TITLE
Allow CKE to backup k8s etcd on localhost

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#697]
## What

Add a utility to dump and save CKE-managed etcd data.

This is to extend the options on where etcd backup data are stored.
For example, with this utility, we can store backups on hosts outside of the cluster.

## How

Add a new subcommand to `ckecli` that connects to an etcd process running on a control-plane node
and dumps all the data within it.

This way, we can easily configure crontab to take backups regularly.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by dulltz** [comment]
Waiting for Ceph
