### ISSUE TITLE
Rook: make light test environment to test OSD on PVC with kind

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#707]
## What

Currently, testing OSD on PVC takes a very long time for each try. We use TopoLVM to provisioning PVCs. However,  setting up TopoLVM is difficult because of the following reasons.

- Use the environment after neco-apps test: It takes a very long time.
- Use TopoLVM in the CKE on VMs: It takes a very long time.
- Use TopoLVM in kind: Setting up TopoLVM properly in kind is almost impossible.

We found using local persistent volume with kind looks fine. Altough TopoLVM's dynamic provisioning feature is very useful, it is not mandatory to test OSD on PVC. Instead, we can test it by preparing PVs before testing.

As a side note, this test environment is useful not only Rook but also all tests that want to use local volumes.

## How

1. Create a big sparse file for each node.
2. Create a lookback device with this file.
3. Create a PhysicalVolume and a VolumeGroup on this device.
4. Create LogicalVolumes from this VolumeGroup.
5. Create a k8s cluster with kind.
6. Create PVs from these LogicalVolumes as local persistent volume. Here we must pay attention to that all LogicalVolumes exist in each node are shared among all nodes. So, if a LogicalVolume is used in a node, this must not be used in other nodes.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Canceled due to inactivity.
