### ISSUE TITLE
Rook: placement doesn't work with OSD on PVC #4582

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#710]
## What

In CephCluster CRD, storage.StorageClassDeviceSets.placement doesn't work.

For more detail, please refer to the following upstream issue.

https://github.com/rook/rook/issues/4582

## How

Depend on the result of discission in Rook community.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@zoetrope will ask the next action on Slack.

**Comment by satoru-takeuchi** [comment]
This issue can be closed after merging the following commit.

https://github.com/rook/rook/pull/4737

**Comment by ymmt2005** [comment]
Got merged.
