### ISSUE TITLE
Run Sonobuoy by CronJob and report its results to push-gateway

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/neco#714]
## What

To ensure the stage/prod k8s cluster is healthy and conformance with CNCF standard.

## How

- Run Sonobuoy by CronJob and report its results to push-gateway.
- Create a dashboard to confirm the results 

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by dulltz** [comment]
Wait for upgrading push gateway to v 1.0
