### ISSUE TITLE
[2019-01-15] Delete gatekeeper 

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#729]
Goals
-----

- Purge gatekeeper

Procedures
----------

Choose one:

### Irregular operation

@stage0-boot-0

```console
$ while true; do if kubectl -n gatekeeper-system patch constrainttemplates.templates.gatekeeper.sh networkpolicyorder --type=json -p '[{"op":"replace","path":"/metadata/finalizers","value":[]}]'; then break; fi; sleep 5; done
$ kubectl delete validatingwebhookconfigurations validation.gatekeeper.sh
$ kubectl delete ns gatekeeper-system
```

Review procedures
-----------------

Confirm that gatekeeper-system namespace does not exist

Write down the instructions for **reviewers** to verify this operation.

(Optional) Check list
---------------------

- [ ] Check xxx

**Comment by ymmt2005** [comment]
Should be on neco-ops repository.
