### ISSUE TITLE
Rook: persistent log and crash

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#736]
## What

Rook/Ceph stores the following three types of data under its data directory (typically /var/lib/rook).

a. User's data
b. MON's data
c. crash and log data

Since Neco uses CoreOS, these data should be persistent explicitly. Currently, we know that (a) and (b) can be persistent by "OSD on PVC" and "MON on PVC". However, there is no such way about (c).

Rook community will support this feature. However, the issue is not available yet.
https://github.com/rook/rook/blob/master/design/ceph/ceph-mon-pv.md

> Logs and crash data. The current implementation continues the use of a HostPath volume based on dataDirHostPath for storing daemon log and crash data. This is a temporary exception that will be resolved as we converge on an approach that works for all Ceph daemon types.

addition:
We don't test the deployment of crashcollector pods. We should consider about testing of it.

### Technical note

- crash information is collected by crashcollector and stored into MON.
- logs can be collected by promtail.

## How

- Add tests
- Configure promtail

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#23
