### ISSUE TITLE
controller-runtime: Sleep for some seconds after receiving signal

### ISSUE THREAD

**Issue by tapih** [cybozu-go/neco#745]
## What

When a Pod is shutting down, pod termination and endpoint deletion are executed at the same time.
The problem is that some requests cannot be accepted if the endpoint deletion does not finish while the pod termination finishes.

One way to wait for endpoint deletion is to add sleep command into `preStop`, but if a base image does not have the `sleep` command, this approach cannot be taken.

In this task, we aim to resolve this problem at the framework level. 

## How

Fix the upstream controller-runtime by inserting sleep just after the controller-runtime's signal handler.

Issue:
https://github.com/kubernetes-sigs/controller-runtime/issues/764

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Closing because the upstream will re-design the signal handling.
