### ISSUE TITLE
maneki-apps: create argocd-config Application

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco#761]
## What

We need an application of applications of ArgoCD for Maneki.

## How

Create an Application of `argocd-config`.
This bundles information of other Maneki applications.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by binoue** [comment]
Created pull request is [here](https://github.com/cybozu-private/maneki-apps/pull/9/)
