### ISSUE TITLE
TopoLVM: write the problem that is pointed out in #97 as a limitation

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#785]
## What

TopoLVM has a problem that is pointed out in the following issue.

https://github.com/cybozu-go/topolvm/issues/97

We should add this problem as a limitation.

## How

Just update docs/limitations.md

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by binoue** [comment]
updated `limitations.md` by [this](https://github.com/cybozu-go/topolvm/commit/be3f7dfb0492f67821de62c61e263d11364ad824)
