### ISSUE TITLE
topolvm: Expose lvmd version as metrics

### ISSUE THREAD

**Issue by dulltz** [cybozu-go/neco#805]
## What

We cannot grasp the version of lvmd service running for each nodes.
Currently, if we do that, we need to ssh for each nodes.

## How

Expose lvmd version as Prometheus metrics like a node-exporter.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
#447 will make sure that all nodes eventually runs the latest `lvmd`.
