### ISSUE TITLE
[neco-apps] ask about how to use Argo CD for multi-tenancy

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#814]
## What

It is not clear about how to use Argo CD for multi-tenancy use.
Ask Argo CD maintainers in Argo CD slack how they are thinking about multi-tenancy and what to do for it.

Currently, this is talked [here](https://bozuman.cybozu.com/k/#/space/3801/thread/38009/2255599)

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
No one is interested.
