### ISSUE TITLE
[sabakan] Improve machine states

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#815]
## What

Sabakan has some unused state and we want to another state, we re-consider and improve them.

- Unused state
  - `unreachable`
     There is almost no difference between `unreachable` and `unhealthy`.
     So we delete the `unreachable` and unify the abnormal states to `unhealthy`.
- New state
  - The state for healthy but not choosable because the machine is used for investigation, benchmark, or etc.

## How

- Remove `unreachable` from sabakan's machines lifecycle.
- Enable to register the reason for becoming `unhealthy`.
- Add a new state for healthy but not choosable.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by kmdkuk** [comment]
The `updating` state will be modified to be used during planned restarts. at https://github.com/cybozu-go/neco/pull/1889
