### ISSUE TITLE
Check the release note of Kubernetes 1.17

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#828]
## What

To conform to kubernetes 1.17, check the release note of this version.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md

## How

Read it and pick the necessary actions.
Necessary actions should be listed as comments for this issue.

e.g. https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/neco/678

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by masa213f** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#storage
>Storage
>A node that uses a CSI raw block volume needs to be drained before kubelet can be upgraded to 1.17. (#74026, @mkimuram)

This is referred to in "Technical information" of EPIC.
We need to drain the pod that matches the conditions.

**Comment by masa213f** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#deprecations-and-removals
> kubeadm.k8s.io/v1beta1 has been deprecated, you should update your config to use newer non-deprecated API versions. (#83276, @Klaven)

delete.
https://github.com/cybozu-go/topolvm/blob/f23d2fffcce46b729132e69574369acb108b6a25/e2e/Makefile#L14-L26

**Comment by masa213f** [comment]
> Deprecate the default service IP CIDR. The previous default was 10.0.0.0/24 which will be removed in 6 months/2 releases. Cluster admins must specify their own desired value, by using --service-cluster-ip-range on kube-apiserver. (#81668, @darshanime)

CKE is already set this flag. We need nothing to do.

https://github.com/cybozu-go/cke/blob/df2f543813695462623f4ca46b4ddd7a435811d9/op/k8s/apiserver_boot.go#L291

**Comment by masa213f** [comment]
> Hyperkube will now be available in a new Github repository and will not be included in the kubernetes release from 1.17 onwards (#83454, @dims)

Should we fix our hyperkube image?
https://github.com/cybozu/neco-containers/blob/520fe02785fb60745f5c82acf5c02171f2b3b3cd/hyperkube/Dockerfile#L43

**Comment by llamerada-jp** [comment]
> All resources within the rbac.authorization.k8s.io/v1alpha1 and rbac.authorization.k8s.io/v1beta1 API groups are deprecated in favor of rbac.authorization.k8s.io/v1, and will no longer be served in v1.20. (#84758, @liggitt)

Should we update resources apiVersion field?
ex: https://github.com/cybozu-go/neco-apps/blob/93f12fb075f77854fe388602c9cd932856dc67b9/ingress/base/global/rbac.yaml#L1

**Comment by dulltz** [comment]
> The CSINodeInfo feature gate is deprecated and will be removed in a future release. The storage.k8s.io/v1beta1 CSINode object is deprecated and will be removed in a future release. (#83474, @msau42)

We should change `storage.k8s.io/v1beta1` to `storage.k8s.io/v1` when upgrading to 1.19.

**Comment by dulltz** [comment]
> Following metrics have been turned off: apiserver_request_count apiserver_request_latencies apiserver_request_latencies_summary apiserver_dropped_requests etcd_request_latencies_summary apiserver_storage_transformation_latencies_microseconds apiserver_storage_data_key_generation_latencies_microseconds apiserver_storage_transformation_failures_total (#83837, @RainbowMango)

We are using the above in dashbords

**Comment by masa213f** [comment]
> Kube-apiserver now reloads serving certificates from disk every minute to allow rotation without restarting the server process (#84200, @jackkleeman)

Just a note: maybe we need not anything.

**Comment by RainbowMango** [comment]
What can I help you guys? :)

**Comment by ymmt2005** [comment]
@masa213f 
> We need to drain the pod that matches the conditions.

Alternatively, we may implement an off-line conversion during
the restart of kubelet in CKE.

**Comment by dulltz** [comment]
@RainbowMango 
Sorry, we accidentally sent many mentions.😨 
We apologize to you...

**Comment by RainbowMango** [comment]
All right!

**Comment by masa213f** [comment]
> When registering with a 1.17+ API server, MutatingWebhookConfiguration and ValidatingWebhookConfiguration objects can now request that only v1 AdmissionReview requests be sent to them. Previously, webhooks were required to support receiving v1beta1 AdmissionReview requests as well for compatibility with API servers <= 1.15.
> - When registering with a 1.17+ API server, a CustomResourceDefinition conversion webhook can now request that only v1 ConversionReview requests be sent to them. Previously, conversion webhooks were required to support receiving v1beta1 ConversionReview requests as well for compatibility with API servers <= 1.15. (#82707,

Should we change the API version in TopoLVM example?
https://github.com/cybozu-go/topolvm/blob/7ffae37dbc07a1aad3562bc883bb7f1b89d993ce/example/kustomization.yaml#L30-L32
