### ISSUE TITLE
Refactor alert rules

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#848]
## What

Refactor alert rules

## How

Check the necessity of refactoring and do it.

1. `AppOutOfSync` may not have `exported_name` label.
https://github.com/cybozu-go/neco-apps/blob/894205b164490d8e3728ebd30ebd83bcefcef87e/monitoring/base/prometheus/alert_rules/argocd.yaml#L10

2. `BootserverEtcdMissing` and `CKEEtcdMissing` should be fired if at least one instance down.
https://github.com/cybozu-go/neco-apps/blob/894205b164490d8e3728ebd30ebd83bcefcef87e/monitoring/base/prometheus/alert_rules/etcd.yaml#L28-L43

3. `InvalidHTTPProxyExist` alert will be solved unintentionally.
https://github.com/cybozu-go/neco-apps/blob/894205b164490d8e3728ebd30ebd83bcefcef87e/monitoring/base/prometheus/alert_rules/ingress.yaml#L58-L66
`rate()` is not good in this case.

4. Delete the constant string (boot0 IP address).
https://github.com/cybozu-go/neco-apps/blob/8ab6a70ba516a346cf8db8890ff2fdc1e8c9ba24/monitoring/base/prometheus/alert_rules/sabakan.yaml#L9

5. MetalLB's `up` metrics cannot be identified as `speaker` and `controller`.
It is better to be able to identify.

6. And should we stop using `absent (up {xxx} == 1)` for DaemonSet?
eg: `CalicoNodeDown`, `MetalLBDown` and so on.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by umezawatakeshi** [comment]
Because `job="teleport"` scrapes pods in several different roles, the following alert rule expression may not trigger an alert if all pods in a certain role are down.
https://github.com/cybozu-go/neco-apps/blob/adb9709612b2f1b796acc8e705e540a6a2f734bf/monitoring/base/prometheus/alert_rules/teleport.yaml#L6

**Comment by umezawatakeshi** [comment]
As written in https://github.com/cybozu-go/neco-apps/blob/87f2fb5397ae2fe16f7adb5a8bec6186c1c09133/monitoring/base/prometheus/README.md, the severity of the alerts are in the order of "critical", "minor", "warning", "info", from highest to lowest. This is consistent with ITU Perceived Severity, but the word "minor" does not indicate how high the severity is. It (or they) might be renamed.
