### ISSUE TITLE
Rook: Resolve the degrade on logical volume backed PVC

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/neco#859]
## What

Resolve the degrade on logical volume backed PVC.
  - Current `rook/rook:master` uses `ceph-volume inventory` command to check the devices are available for Ceph OSD or not. However, this command cannot be used for logical volume. So, logical volume backed PVC does not work.
   - Our workingaround: https://github.com/cybozu-go/rook/commit/517f46227787a2eff89e2bcedced2c779582c5ad

## How

1. Post an issue to `rook/rook`

2. Prepare a PR based on discussion with the Rook comunity

## Issue and PR on the Upstream

issue: https://github.com/rook/rook/issues/5075
PR: https://github.com/rook/rook/pull/5101

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by morimoto-cybozu** [comment]
I submitted an issue.
https://github.com/rook/rook/issues/5075
