### ISSUE TITLE
[Rook] Propose the division of common.yaml

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#860]
## What

[common.yaml](https://github.com/rook/rook/blob/14a713107af21f84413cd320abecfd2493459cc2/cluster/examples/kubernetes/ceph/common.yaml) in Rook contains namespaced resources and cluster-wide resources disorderly.
As a result, to create two different ceph cluster, we need to divide the resources in`common.yaml` into namespaced resources and cluster-wide resources one by one whenever rook updates.

As this is costly, we should propose to divide `common.yaml` into multiple yaml files.

## How

Create an issue for rook.
Issue: https://github.com/rook/rook/issues/5049
PR: 
- https://github.com/rook/rook/pull/5240: splitted into the following PRs
   - https://github.com/rook/rook/pull/5297: merged
   - https://github.com/rook/rook/pull/5445: merged
   - https://github.com/rook/rook/pull/5334: merged
   - https://github.com/rook/rook/pull/5573: progressing

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by binoue** [comment]
PR: https://github.com/rook/rook/pull/5573

**Comment by binoue** [comment]
waiting for https://github.com/rook/rook/pull/5844

**Comment by ymmt2005** [comment]
https://github.com/rook/rook/pull/5573 marked as stale.
