### ISSUE TITLE
rook: make it possible to run the integration test in local environment

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#868]
## What

Although the Integration test works fine in CI environment,  it doesn't work in local environmet.

## How

Depends on the discussion with upstream community.

PR
https://github.com/rook/rook/pull/4966

I guess there are at least two commits to resolve this issue.

- Make it possible to pass all tests in the local test environment. Currently, many of them failed even if these tests pass in the CI environment.
- Make it possible to run and pass the OSD on non-LV backed PVC. Currently, this test only runs in the CI environment. 

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by satoru-takeuchi** [comment]
Prevent deleting all pre-existing LVMs at the beginning of the integration test: Wait to be merged.
https://github.com/rook/rook/pull/5058

Make it possible to pass the integration test of OSD: No PR yet.

Make it possible to run the integration test of OSD on non-LV backed PVC: No PR yet.

**Comment by ymmt2005** [comment]
@satoru-takeuchi done?

**Comment by satoru-takeuchi** [comment]
@ymmt yes. Please close this.
