### ISSUE TITLE
Grafana: Add dashboard for for checking NotReady Nodes

### ISSUE THREAD

**Issue by tapih** [cybozu-go/neco#907]
## What

Add dashboard to grafana for checking NotReady Nodes.

## How

Use the `kube_node_status_condition` metrics exposed by kube-state-metrics.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by dulltz** [comment]
duplicate #902
