### ISSUE TITLE
neco-apps: stabilize bmc-reverse-proxy test

### ISSUE THREAD

**Issue by umezawatakeshi** [cybozu-go/neco#908]
## What

neco-apps test somestimes fails at https://github.com/cybozu-go/neco-apps/blob/master/test/setup_test.go#L350

This might be caused by absence of configmap.

## How

Add sync wave for configmap.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Rather than setting `sync-wave` to ConfigMap, it'd be better to leave it as default.
Since the default wave is zero.

Ref: https://argoproj.github.io/argo-cd/user-guide/sync-waves/#how-do-i-configure-waves

Instead, set higher wave to the Deployment.

**Comment by tapih** [comment]
Implemented in https://github.com/cybozu-go/neco-apps/pull/491.
