### ISSUE TITLE
[neco/dctest] Configurable GCP region/zone for CircleCI

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#929]
## What

The GCP region/zone for CircleCI is [hardcoded](https://github.com/cybozu-go/neco/blob/71d636d9cd6c615b73dedb57bb68aefa64075608/gcp/config.go#L110).
So it is difficult to switch the region when a failure occurs in that region.

Need to modify the following repositories:
- coil
- sabakan
- neco
- cke
- etcdpassw
- placemat

## How

TBD

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
not worth doing.
