### ISSUE TITLE
replace the container image used by Rook/Ceph with ourself build

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/neco#940]
## What

Make the following container images used by Rook/Ceph at `quay.io/cybozu`.
And use it at Rook/Ceph.

- quay.io/cephcsi/cephcsi:v2.0.1
- quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
- quay.io/k8scsi/csi-resizer:v0.4.0
- quay.io/k8scsi/csi-provisioner:v1.4.0
- quay.io/k8scsi/csi-snapshotter:v1.2.2
- quay.io/k8scsi/csi-attacher:v2.1.0

## How

- Add entries for neco-containers to make each container.
- Replace images on the rook's manifest  `operator.yaml`.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
move to cybozu/csa#21
