### ISSUE TITLE
ceph: support mode-specific availability fields in ceph-volume inventory

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#944]
## What

To resolve the following task, we should add the mode-specific availability fields in `ceph-volume inventory` as a prerequisite.

https://github.com/cybozu-go/neco/issues/943

"raw mode", that Rook uses, can create OSDs on top of virtually any type devices. However, the traditional "LVM mode" only supports "disk" type devices and "part" type devices. However, `ceph-volume inventory` only considers "LVM mode".  So, even though there is a clean dm-crypt HDD, this device is reported as unavailable by `ceph-volume inventory`.

upstream issue:
https://tracker.ceph.com/issues/45443

## How

Depending on the discussion in the upstream community.

Merging the following two PR is required.

not merged yet
https://github.com/ceph/ceph/pull/34966

merged:
https://github.com/ceph/ceph/pull/35190

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by llamerada-jp** [comment]
new PR at upstream
https://github.com/ceph/ceph/pull/34966

**Comment by satoru-takeuchi** [comment]
> Merging the following two PR is required.
> 
> https://github.com/ceph/ceph/pull/34966
> https://github.com/ceph/ceph/pull/35190

34966 is merged.
