### ISSUE TITLE
[Jun 1st] Resizing the prometheus volume for investigating an error 

### ISSUE THREAD

**Issue by binoue** [cybozu-go/neco#973]
## What

- In the previous resizing operation for the prometheus volume, we encountered an error of volume expansion.
Try to resize again to confirm this error is reproducible and fix the error if it exists.
- See more details [here](https://bozuman.cybozu.com/k/#/space/3801/thread/25931/2382843)

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Due on Jun. 1st.

**Comment by ymmt2005** [comment]
We could reproduce the problem.
