### ISSUE TITLE
Argocd app remains OutOfSync due to app.kubernetes.io/instance: argocd label diff

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/neco#992]
## What

https://github.com/argoproj/argo-cd/issues/3603

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ysksuzuki** [comment]
The problem hasn't occurred since we updated Argocd to v1.5.6. I'll close the upstream issue as well.
